name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          
      - name: Run tests on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: tox 

      # - name: Run tests on Windows
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   run: tox -e py${{ matrix.python-version }}

      # - name: Run tests on MacOS-latest
      #   if: ${{ matrix.os == 'macos-latest' }}
      #   # https://github.com/actions/runner-images/issues/1280#issuecomment-662839485
      #   run: FC=gfortran-12 tox -e py${{ matrix.python-version }}
